name: Release Stable

on:
  workflow_run:
    workflows: ["nimbus - CI"]
    types: [completed]
    branches:
      - stable
      - staging

jobs:
  release:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write
      pull-requests: write
      id-token: write
      issues: write

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          target-branch: ${{ github.event.workflow_run.head_branch }}
          config-file: release-config.json
          manifest-file: .release-manifest.json

  build:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}

    strategy:
      matrix:
        app: ["frontend"]
        output-dir: ["front-dist"]

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Build
        run: |
          cd ${{ matrix.app }}
          bun ci
          bun build ./src/index.ts --outdir ./${{ matrix.output-dir }} --target=bun
          cd -

      - name: Upload to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.release.outputs.tag_name }} ${{ matrix.app }}/${{ matrix.output-dir }}/*